name: SoC Course Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *" # 01:30 Asia/Singapore
    - cron: "30 5 * * *" # 13:30 Asia/Singapore

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          path: repo
          ref: soc-sched

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: ./update-sched.sh

      - run: git -C repo push
